.PHONY: clean All

All:
	@echo "----------Building project:[ HelloWorld - Debug ]----------"
	@cd "HelloTesting" && "$(MAKE)" -f  "HelloWorld.mk"
clean:
	@echo "----------Cleaning project:[ HelloWorld - Debug ]----------"
	@cd "HelloTesting" && "$(MAKE)" -f  "HelloWorld.mk" clean
