.PHONY: clean All

All:
	@echo "----------Building project:[ FirstRealProgram - Debug ]----------"
	@cd "FirstRealProgram" && "$(MAKE)" -f  "FirstRealProgram.mk"
clean:
	@echo "----------Cleaning project:[ FirstRealProgram - Debug ]----------"
	@cd "FirstRealProgram" && "$(MAKE)" -f  "FirstRealProgram.mk" clean
